# Generated by Django 3.0 on 2019-12-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('scroll', models.IntegerField()),
                ('amount_request', models.BigIntegerField()),
                ('amount_approve', models.BigIntegerField()),
                ('date_create', models.DateTimeField(verbose_name='date create')),
                ('status', models.CharField(choices=[('wait', 'Waiting'), ('approve', 'Approved'), ('reject', 'Rejected')], max_length=50)),
            ],
        ),
    ]
